### ISSUE TITLE
Charset is ignored when using a connection pool

### ISSUE THREAD

**Issue by FedericoBiccheddu** [MariaDB/mariadb-connector-nodejs#38] opened 2019-01-10 15:36 UTC
While I'm using a connection pool (with `createPool` method), the charset is not used anymore resulting in a encoding problem after the connection is used like 1/5 of the limit (eg: if `connectionLimit` is set to 10, after 4 queries the result changes).

Correct result: `Snax, byali и TOAO войдут в новый состав по CS:GO`
Actual result: `Snax, byali ? TOAO ?????? ? ????? ?????? ?? CS:GO` 

Even using `CONVERT()` or `CAST()` the problem persists.

This is the connection snippet:
```js
const mariadb = require('mariadb');
const database = mariadb.createPool({
    host: process.env.DATABASE_HOST,
    user: process.env.DATABASE_USERNAME,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_NAME,
    timezone: 'Z'
    acquireTimeout: 2000
});
```

and the table structure:
```sql
CREATE TABLE `course_content` (
  `course` char(36) CHARACTER SET ascii NOT NULL,
  `content` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

**Node**: v10.13.0
**MariaDB**: 10.2
**MariaDB Connector**: 2.0.2-rc

**Comment by knoxcard** [comment] 2019-01-10 16:09
```
var sequelize = new Sequelize(nconf.get('database:db'), nconf.get('database:user'), nconf.get('database:pass'), {
  port: nconf.get('database:port'),
  pool: {
    min: 1,
    max: 60,
    idle: 100000
  },
  define: {
    charset: 'utf8mb4',
    timestamps: false,
    dialectOptions: {
      collate: 'utf8mb4_general_ci'
    }
  },
  dialect: 'mariadb',
  dialectOptions: {
    supportBigNumbers: true,
    bigNumberStrings: true
  },
  benchmark: false,
  logging: true
})
```

**Comment by FedericoBiccheddu** [comment] 2019-01-11 14:06
Maybe can help: with the `2.0.0-alpha` version the problem is not present.
`2.0.0-beta` same result as `2.0.2-rc`.

**Comment by rusher** [comment] 2019-01-15 15:35
hi @FedericoBiccheddu. I've didn't reproduced any issue for the moment. 
Can you try adding `resetAfterUse` to false in pool configuration?
```javascript
const database = mariadb.createPool({
    host: process.env.DATABASE_HOST,
    user: process.env.DATABASE_USERNAME,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_NAME,
    timezone: 'Z',
    resetAfterUse: false,
    acquireTimeout: 2000
});
```

`resetAfterUse` is an internal option to indicate that when server has this feature to reset connection state with a  [COM_RESET_CONNECTION ](https://mariadb.com/kb/en/library/com_reset_connection/) packet to server). 
This command is executed when giving back connection to pool, that would correspond to the issue occuring only after some queries. 

This normally doesn't change charset, but I don't see any other possibility for now.

**Comment by FedericoBiccheddu** [comment] 2019-01-15 18:41
Hi @rusher, thank you for the response. Setting `resetAfterUse` to `false` resolves the problem.

**Comment by FedericoBiccheddu** [comment] 2019-01-16 11:45
@knoxcard I didn't close the issue because, as @rusher said, I don't know if the issue is really resolved or it is a side-effect.

@rusher:
```
Variable_name | Value
-- | --
character_set_client | utf8mb4
character_set_connection | utf8mb4
character_set_database | utf8mb4
character_set_filesystem | binary
character_set_results | utf8mb4
character_set_server | latin1
character_set_system | utf8
character_sets_dir | /usr/share/mysql/charsets/
```
```
Variable_name | Value
-- | --
collation_connection | utf8mb4_general_ci
collation_database | utf8mb4_unicode_520_ci
collation_server | latin1_swedish_ci
```
<details><summary>This is the `my.cnf` content:</summary>

```ini
# MariaDB database server configuration file.
#
# You can copy this file to one of:
# - "/etc/mysql/my.cnf" to set global options,
# - "~/.my.cnf" to set user-specific options.
# 
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

# This will be passed to all mysql clients
# It has been reported that passwords should be enclosed with ticks/quotes
# escpecially if they contain "#" chars...
# Remember to edit /etc/mysql/debian.cnf when changing the socket location.
[client]
port            = 3306
socket          = /var/run/mysqld/mysqld.sock

# Here is entries for some specific programs
# The following values assume you have at least 32M ram

# This was formally known as [safe_mysqld]. Both versions are currently parsed.
[mysqld_safe]
socket          = /var/run/mysqld/mysqld.sock
nice            = 0

[mysqld]
#
# * Basic Settings
#
#user           = mysql
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
port            = 3306
basedir         = /usr
datadir         = /var/lib/mysql
tmpdir          = /tmp
lc_messages_dir = /usr/share/mysql
lc_messages     = en_US
skip-external-locking
#
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
#bind-address           = 127.0.0.1
#
# * Fine Tuning
#
max_connections         = 100
connect_timeout         = 5
wait_timeout            = 600
max_allowed_packet      = 16M
thread_cache_size       = 128
sort_buffer_size        = 4M
bulk_insert_buffer_size = 16M
tmp_table_size          = 32M
max_heap_table_size     = 32M
#
# * MyISAM
#
# This replaces the startup script and checks MyISAM tables if needed
# the first time they are touched. On error, make copy and try a repair.
myisam_recover_options = BACKUP
key_buffer_size         = 128M
#open-files-limit       = 2000
table_open_cache        = 400
myisam_sort_buffer_size = 512M
concurrent_insert       = 2
read_buffer_size        = 2M
read_rnd_buffer_size    = 1M
#
# * Query Cache Configuration
#
# Cache only tiny result sets, so we can fit more in the query cache.
query_cache_limit               = 128K
query_cache_size                = 64M
# for more write intensive setups, set to DEMAND or OFF
#query_cache_type               = DEMAND
#
# * Logging and Replication
#
# Both location gets rotated by the cronjob.
# Be aware that this log type is a performance killer.
# As of 5.1 you can enable the log at runtime!
#general_log_file        = /var/log/mysql/mysql.log
#general_log             = 1
#
# Error logging goes to syslog due to /etc/mysql/conf.d/mysqld_safe_syslog.cnf.
#
# we do want to know about network errors and such
#log_warnings           = 2
#
# Enable the slow query log to see queries with especially long duration
#slow_query_log[={0|1}]
slow_query_log_file     = /var/log/mysql/mariadb-slow.log
long_query_time = 10
#log_slow_rate_limit    = 1000
#log_slow_verbosity     = query_plan

#log-queries-not-using-indexes
#log_slow_admin_statements
#
# The following can be used as easy to replay backup logs or for replication.
# note: if you are setting up a replication slave, see README.Debian about
#       other settings you may need to change.
#server-id              = 1
#report_host            = master1
#auto_increment_increment = 2
#auto_increment_offset  = 1
#log_bin                        = /var/log/mysql/mariadb-bin
#log_bin_index          = /var/log/mysql/mariadb-bin.index
# not fab for performance, but safer
#sync_binlog            = 1
expire_logs_days        = 10
max_binlog_size         = 100M
# slaves
#relay_log              = /var/log/mysql/relay-bin
#relay_log_index        = /var/log/mysql/relay-bin.index
#relay_log_info_file    = /var/log/mysql/relay-bin.info
#log_slave_updates
#read_only
#
# If applications support it, this stricter sql_mode prevents some
# mistakes like inserting invalid dates etc.
#sql_mode               = NO_ENGINE_SUBSTITUTION,TRADITIONAL
#
# * InnoDB
#
# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
default_storage_engine  = InnoDB
# you can't just change log file size, requires special procedure
#innodb_log_file_size   = 50M
innodb_buffer_pool_size = 256M
innodb_log_buffer_size  = 8M
innodb_file_per_table   = 1
innodb_open_files       = 400
innodb_io_capacity      = 400
innodb_flush_method     = O_DIRECT
#
# * Security Features
#
# Read the manual, too, if you want chroot!
# chroot = /var/lib/mysql/
#
# For generating SSL certificates I recommend the OpenSSL GUI "tinyca".
#
# ssl-ca=/etc/mysql/cacert.pem
# ssl-cert=/etc/mysql/server-cert.pem
# ssl-key=/etc/mysql/server-key.pem

#
# * Galera-related settings
#
[galera]
# Mandatory settings
#wsrep_on=ON
#wsrep_provider=
#wsrep_cluster_address=
#binlog_format=row
#default_storage_engine=InnoDB
#innodb_autoinc_lock_mode=2
#
# Allow server to accept connections on all interfaces.
#
#bind-address=0.0.0.0
#
# Optional setting
#wsrep_slave_threads=1
#innodb_flush_log_at_trx_commit=0

[mysqldump]
quick
quote-names
max_allowed_packet      = 16M

[mysql]
#no-auto-rehash # faster start of mysql but no tab completion

[isamchk]
key_buffer              = 16M

#
# * IMPORTANT: Additional settings that can override those from this file!
#   The files must end with '.cnf', otherwise they'll be ignored.
#
!includedir /etc/mysql/conf.d/
```

</details>


Changing the mariadb docker image to `"mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci --init-connect='SET NAMES UTF8;'"` and removing `resetAfterUse` the problem is not showing anymore.

**Comment by rusher** [comment] 2019-01-16 16:32
That's what I suspected, I will do some testing tomorrow, but it seems that when executing the reset, the server even reset the connection character encoding to server default encoding.

**Comment by rusher** [comment] 2019-01-17 10:37
server issue created: https://jira.mariadb.org/browse/MDEV-18281

**Comment by FedericoBiccheddu** [comment] 2019-01-17 11:58
Hi @rusher, thank you so much for the support.

For now I would stick with the custom command until the issue it will be fixed.

**Comment by rusher** [comment] 2019-01-21 15:08
Closing the issue, since it's not connector side

**Closed by rusher** 2019-01-21 15:08 UTC
