### ISSUE TITLE
Knex - next major integration

### ISSUE THREAD

**Issue by knoxcard** [MariaDB/mariadb-connector-nodejs#57] opened 2019-06-04 05:01 UTC
The Sequelize integration was incredible!  Ready for Knex?

**Wondering if everything already works?**
Once I test it out...I'll let you know

**Knex**
https://www.npmjs.com/package/knex
Weekly Downloads: 283,939

**Node.js**
The primary target environment for Knex is Node.js, you will need to install the knex library, and then install the appropriate database library: pg for PostgreSQL and Amazon Redshift, mysql for MySQL or MariaDB, sqlite3 for SQLite3, or mssql for MSSQL.

$ npm install knex --save

### # Then add one of the following (adding a --save) flag:
```
$ npm install pg
$ npm install sqlite3
$ npm install mysql
$ npm install mysql2
$ npm install oracle
$ npm install mssql

```
---> ### If you want to use a MariaDB instance, you can use the mysql driver.

**Comment by knoxcard** [comment] 2019-06-04 05:07
Just a thought, when developers see a high number of "issues", they might suspect the package to be "bad".

Instead of me posting these particular topics as issues, maybe we could set this up?
https://github.com/MariaDB/mariadb-connector-nodejs/projects

Thanks for the great work!

**Comment by rusher** [comment] 2019-06-06 09:04
In fact, since it's not an issue, the best place is on MariaDB tracker: https://jira.mariadb.org/projects/CONJS/
I've recreated this task: https://jira.mariadb.org/browse/CONJS-80 and will close this issue. 

(that's not as direct than GitHub issue, but that has other advantages)

**Closed by rusher** 2019-06-06 09:04 UTC

**Comment by Zikoel** [comment] 2025-10-08 10:03
@rusher a problem with jira is that no one can comment issues. In this case for example the issue is untouched from its creation. I would comment on jira but I cannot. There are news about knex integration ? There are problems using `mysql` with knex and this driver ?
